### PR TITLE
Add the ability to specify the format of the image

### PR DESCRIPTION
**Pull request by RubenVanEldik**
Add an 'f' parameter which will set the contentType. This parameter can be either one of 'png', 'jpeg', 'webp', or 'auto'.

The auto parameter will look at the accept headers, if the browser accepts webp, it will use that, otherwise it will return the contentType of the image itself.

### CODE REVIEW

**Comment by RubenVanEldik** [comment]
I've also tried to add the AVIF format as auto format, since it seems like its the format [of the future](https://creativepro.com/webp-and-avif-file-formats-you-need-to-know-about/), but the file savings were marginal and the processing time grew immensely. For some larger images to more than 20 seconds! I think sharp is not yet capable of transforming to AVIF efficiently yet.

**Comment by elitan** [comment]
Do we also want to do a [`transformer.toFormat(f)`](https://sharp.pixelplumbing.com/api-output#toformat) here and actually change the format of the image?

**Comment by RubenVanEldik** [comment]
I thought this was already done by these lines?

```
    if (contentType === WEBP) {
        transformer.webp({ quality: q })
      } else if (contentType === PNG) {
        transformer.png({ quality: q })
      } else if (contentType === JPEG) {
        transformer.jpeg({ quality: q })
      }```

**Comment by elitan** [comment]
> I thought this was already done by these lines:
> 
> https://github.com/nhost/hasura-backend-plus/blob/663d60da99bebb67fa665fe5c63d2f5786514802/src/routes/storage/get.ts#L66-L72

This is only to set quality for images that are already in a certain format.

I was think also that `headObject.ContentType` is in the correct format for existing images.

I was thinking that this `f` (or `format`) parameter would transform images to the format specified. Ex: `.../storage/o/image.jpg?format=png` would transform the image from jpg to png and set the correct contentType headers.

**Comment by RubenVanEldik** [comment]
This was indeed my intention, but you're right and the image is not converted yet. I'll create a new PR this weekend! :)

**Comment by elitan** [comment]
Nice, then we're on the same page. I think it's only a single line of code that's missing basically (`transformer.toFormat(f)`).

**Comment by RubenVanEldik** [comment]
https://github.com/nhost/hasura-backend-plus/pull/463

**Pull request closed without merging**
