### PR TITLE
Make OAuth scopes configurable

### PR DESCRIPTION
**Pull request by Yagger**
The topic was briefly touched [here](https://github.com/nhost/hasura-backend-plus/pull/395), but this PR only touches the scopes configuration-ability.

### CODE REVIEW

**Comment by elitan** [comment]
Amazing PR. I'll check in the coming day!

**Comment by Yagger** [comment]
I started to think whether this PR is actually needed. Because providers let you select scopes for the app in the admin console. For example when you create Google project and setup consent screen for it, you can choose what scopes you require.

But then checked other providers and discovered that not all of them let you select scopes in admin. For example Spotify developer app admin page is very basic - you only get client_id and secret, set redirect url and that's it, no scopes. So you have to explicitly request scopes during the oauth handshake.

So, some providers allow to setup scopes in their admin console and make it implicit, and some providers require scopes to be passed explicitly during the oauth process, and for these providers scopes need to be configurable via env vars.

Interesting how OAuth protocol handles situation when scopes are setup in admin console and different set of scopes is passed via the oauth request. What will be the resulting set of scopes - sum or intersection or.....haven't tested.

**Comment by elitan** [comment]
Let's unify our discussions around this here: https://github.com/nhost/hasura-backend-plus/issues/405 (maybe also add your insights about scopes there too)?

**Comment by elitan** [comment]
Fixed in https://github.com/nhost/hasura-backend-plus/pull/554

**Pull request closed without merging**
