### PR TITLE
Optionally save OAuth token in database

### PR DESCRIPTION
**Pull request by SkinyMonkey**
Allow a developer to avoid program a standalone a way to access the user's data on the aimed service.

### CODE REVIEW

**Comment by SkinyMonkey** [comment]
I just noticed that I didn't touch the migration script, can someone help me with that?

Do you have a way to make columns optional?

**Comment by SkinyMonkey** [comment]
Woops, i'm also inserting the tokens in cases where it should be optional.
I'll fix this!

**Comment by KingBoomie** [comment]
as a comparison, I also implemented this in my fork https://github.com/randomforest-jaant/hasura-backend-plus. Hopefully it will get merged into mainline.

**Comment by Yagger** [comment]
Do I understand correctly that @elitan's initial idea is to use OAuth providers to signin/signup only? Accessing provider's API was not in feature list. So currently what happens after OAuth successfully returns the token, is HBP creates session and returns JWT refresh_token, **but the provider's token is discarded**.

I am just trying to think, what can I do now if I login with Google and then also need to access it's API. Do I need to re-implement the OAuth process in my frontend  (like "connect Google" button) to get the token and then save it in Hasura DB manually.

And this PR (as well as @KingBoomie's implementation) is about optionally keeping the provider's token and refresh token in account_providers table instead of discarding it? So you can immediately access it and start using provider's API on user's behalf.

@elitan, @SkinyMonkey, @KingBoomie did I described correctly how it works now and what this PR is about?

**Comment by elitan** [comment]
Yes the current implementation of HBP is for authentication only without interacting with the provider's API.

The reason I've been staling this PR and those alike is that I have not researched how to handle providers tokens and refresh tokens. Let's solve that discussion here: https://github.com/nhost/hasura-backend-plus/issues/405

**Comment by komninoschat** [comment]
Tracked in #476.

**Pull request closed without merging**
