### PR TITLE
Add the option to specify how to crop an image

### PR DESCRIPTION
**Pull request by RubenVanEldik**

### CODE REVIEW

**Comment by RubenVanEldik** [comment]
This is my last PR for now. I think with the current 7 parameters we've copied all the core image manipulation features from services like Imgix and ImageKit! 🎉 

The only feature that we currently don't yet have is to specify the [type of fit](https://sharp.pixelplumbing.com/api-resize#resize) (e.g. `cover`, `contain`, `fill`, etc.), currently its always the default 'cover'. But I think this is not really a useful feature for 99% of the users. If you want te implement this, please let me know, I'll add it later this week! But a problem is that we'll than also have to rename the format (`f`) parameter to something like type (`t`) because the `f` is most logical for fit, I think. And we'll also need to add a background color (`c`, maybe?) parameter, since the `inside` and `outside` fit add padding, which needs to be given a color. (this color property can than also be used for the background color of the rounding, although there is the background color less important.

**Comment by elitan** [comment]
@RubenVanEldik Amazing work with the PRs!

We could use the full word for parameters that are not commonly used.

width - w
height - h
quality - q
blur - b
format - f (or format so it's not confused with fit)
fit - fit
etc

**Comment by elitan** [comment]
Imgix is using `fm` for `format` [link](https://docs.imgix.com/apis/rendering/format) and `fit` for `fit` [link](https://docs.imgix.com/apis/rendering/size/fit)

**Comment by RubenVanEldik** [comment]
That's a good idea! I tried to keep everything a single character, to not change the spec, but if we want to expand these functionalities in the future this might be more maintainable.

So then you have the option to use both the full name (`width`) and the shorthand (`w`) for the more common names?

**Comment by elitan** [comment]
> That's a good idea! I tried to keep everything a single character, to not change the spec, but if we want to expand these functionalities in the future this might be more maintainable.

Yes


> So then you have the option to use both the full name (`width`) and the shorthand (`w`) for the more common names?

We could do that in a separate PR.

For this PR I think we should:

- Implement position (or maybe call it `crop`? [imgix](https://docs.imgix.com/apis/rendering/size/crop)).
- Implement fit

**Comment by RubenVanEldik** [comment]
I agree with your scope of this PR. I will create another PR to add the full name for all parameters, because I think its confusing if some parameters are only available as shorthand and some as the full name.

Regarding `position` vs `crop`. I don't know yet, I've written a few example out to see what looks more natural, but I don't really have a strong preference. Do you?

`?w=300&position=top` or `?w=300&crop=top`
`?w=1200&q=80&position=attention` or `?w=300&q=80&crop=attention`

**Comment by RubenVanEldik** [comment]
I just see that ImageKit also uses `crop` in their documentation, so I think `crop` might be better. Even if only to go along with the industry best practices. 🙃

**Comment by RubenVanEldik** [comment]
https://github.com/nhost/hasura-backend-plus/pull/463

**Pull request closed without merging**
