### PR TITLE
Update default port in README.md

### PR DESCRIPTION
**Pull request by aaronhayes**

### CODE REVIEW

**Comment by elitan** [comment]
Hi and thanks for the PR.

There are some more places the default port needs to be updated: https://github.com/nhost/hasura-backend-plus/search?utf8=%E2%9C%93&q=port&type=

Could you update those too in this PR?

**Comment by aaronhayes** [comment]
Actually, this is the only place the default port is referenced. The other examples use  the `PORT` environment variable to set a custom port, both examples use `3000` as the custom port. 

I'm happy to update those examples, but they don't reference the default port. Your call.

**Comment by elitan** [comment]
Yea that's true. But I still think it's a good idea to have all ports as `3010`. If you update it I'll merge it ASAP.

**Comment by aaronhayes** [comment]
fair enough. all done now @elitan

**Comment by aaronhayes** [comment]
@elitan this is ready to merge

**Comment by elitan** [comment]
Thank you so much.

**Pull request merged**
