### PR TITLE
Magic links or passwordless login auth provider

### PR DESCRIPTION
**Pull request by weyert**
feat: Add feature to allow users to login into the web application using a magic link which is sent to the user's known email address or also known as passwordless login

### CODE REVIEW

**Comment by elitan** [comment]
This looks very cool. @weyert There are some conflicts here. Would you mind fix them and I'll make time to test this feature next week 👍

**Comment by JStumpp** [comment]
@weyert can you fix the merge conflicts or do you need help? I would really like to see this in the project. Thanks!

**Comment by weyert** [comment]
Sure, I can have a look at it tomorrow :)

**Comment by weyert** [comment]
Merged master back into my branch

**Comment by JStumpp** [comment]
@weyert it looks like a few imports changed. Can you fix this? Thanks.

**Comment by weyert** [comment]
Oh, I will go through it more thoroughly over the weekend. Sorry, been busy with work deadline

**Comment by mnlbox** [comment]
@weyert Interesting PR. Really wait for see this in HBP :eyes:

**Comment by ctwhome** [comment]
@weyert looking forward to this!

**Comment by joshhopkins** [comment]
Any progress here @weyert?

**Comment by elitan** [comment]
Possible we could use this one instead. I have not compared the repos. I just noted that this one got more stars.

https://github.com/mxstbr/passport-magic-login

**Comment by elitan** [comment]
Closing this in favour of https://github.com/nhost/hasura-backend-plus/pull/465

**Pull request closed without merging**
