### PR TITLE
Anonymous registration (and signin)

### PR DESCRIPTION
**Pull request by elitan**
Similar to https://firebase.google.com/docs/auth/web/anonymous-auth

Allow for users to sign in anonymously

- [ ] ENV var to activate this feature (default to false)

### CODE REVIEW

**Comment by elitan** [comment]
> How would the registration (set email, password etc) of anonymous account work?

[next] :D

Firebase got this:
https://stackoverflow.com/questions/39088876/firebase-convert-anonymous-user-account-to-permanent-account-error

**Comment by elitan** [comment]
Maybe we should wait of merging this before we got some kind of linking possibilities?

**Comment by plmercereau** [comment]
Ok I will work on it tonight

**Comment by smblee** [comment]
Why was this PR closed?

**Pull request closed without merging**
