### PR TITLE
Add SMS MFA

### PR DESCRIPTION
**Pull request by joshmedeski**
Closes https://github.com/nhost/hasura-backend-plus/issues/508

# Summary

Adds SMS two-factor authentication to accounts.

# Technical Outline

- Added `/auth/mfa/sms` routes that mirror `/auth/mfa` routes
- Added logic to allow users to use an authenticator or sms
- `POST /auth/mfa/sms/generate` endpoint sends an SMS to the phone number
- `POST /auth/mfa/sms/resend` endpoint was added so users can retrigger a valid SMS code
- `POST /auth/mfa/totp` endpoint is backward compatible and works with an authenticator or SMS code. The code asserts the code using `otp_secret` and `sms_otp_secret` before failing.
- MFA and SMS MFA can be enabled/disabled independently
- Login returns `{ mfa: true, sms_mfa: true }` so the client can create a UI that reflects what MFA type is enabled.
- [Amazon SNS](https://aws.amazon.com/sns/) is used to configure SMS sending. Very similar configuration to how S3 is coded.

### CODE REVIEW

**Comment by joshmedeski** [comment]
I'm waiting to get a valid SNS account to do thorough testing on the AWS SNS features.

**Comment by elitan** [comment]
Really cool! Thanks for the PR.

I'm thinking if we should abstract the SMS sending so we could use other providers such as Twilio or other local SMS services. In Sweden services like https://www.cellsynt.com/sv/ and https://46elks.se/ are popular.

So for `sendSms` we could have different providers and then use env vars to specify which SMS provider is in use.

**Comment by joshmedeski** [comment]
@elitan I was thinking the same thing, however, due to time constraints for a work project I wanted to get an AWS compatible solution working now and abstract it later.

**Comment by joshmedeski** [comment]
@elitan how do you set up the CI tool for testing? I want to make sure these unit tests work.

**Comment by elitan** [comment]
@joshmedeski This is a massive PR and much appreciated. But we've decided to only do bug fixes on this repo and focus new features on a new repo that we hope to share soon. So I'll close this one for now.

**Pull request closed without merging**
