### PR TITLE
fix: support \n in JWT_KEY

### PR DESCRIPTION
**Pull request by zbeyens**
### Issue
The env variable is keeping `\n` characters in its string.

### Solution
Replace `\n` by an actual line break.

### CODE REVIEW

**Review by elitan — APPROVED** [review]

**Comment by elitan** [comment]
Can we provide some tests for t

**Comment by johannesschobel** [comment]
just curious, why this is with the `JWT_KEY` parameter, but not with the other params, like `JWT_CLAIM` or `JWT_ALGORITHM`?! 🤔

**Comment by elitan** [comment]
@zbeyens could you update this PR to merge into `master` (instead of `master-old`). We've been updating the branches a bit so that's why things are a bit out of sync in this PR.

**Comment by johannesschobel** [comment]
dear @elitan ,
just curious, why this issue appears on the `JWT_KEY` and not on the `JWT_ALGORITHM` parameter?! the PR that was merged will solve the issue (obviously) but does actually not target the real source of the issue, right?!

All the best

**Comment by elitan** [comment]
The `JWT_ALGORITHM` is not a long string containing potential `\n`.

**Pull request merged**
