### PR TITLE
Add the 'format', 'fit', and 'crop' parameters

### PR DESCRIPTION
**Pull request by RubenVanEldik**
I created a new PR for https://github.com/nhost/hasura-backend-plus/pull/445 and https://github.com/nhost/hasura-backend-plus/pull/448, because I rewrote some of the existing code around the image transformations and I didn't know if it is possible to create PR's that are based off each other.

This PR has a few features around the image transformations:
1. Allow both shorthand and full name for the parameters (e.g. both `r`, and `radius`)
2. Add the `format` parameter to alter the image format (`auto` is awesome and tries to return the most modern type of image that the browser accepts)
3. Add the `fit` and `crop` parameters
4. Ensure that the image returned is never larger than the original (in the current version it is possible to say `&w=8000` and it will return a super large image that is not better in any way.
5. Update the docs

I hope this PR helps! If I need to break it up into multiple PR's, please let me know. :)

### CODE REVIEW

**Comment by elitan** [comment]
Amazing @RubenVanEldik.

Can you check the tests and make sure they run properly?

**Comment by RubenVanEldik** [comment]
I see there are some issues with the possible `undefined` cases, will fix it now!

**Comment by elitan** [comment]
To test locally do:

```
cp .env.ci .env.test
./start.sh test
```

**Comment by RubenVanEldik** [comment]
Thanks! That's indeed easier than Github Actions 🙃

**Comment by elitan** [comment]
This is an amazing PR @RubenVanEldik but we've decided to only merge bug fixes from now on.

All new features and efforts go into a new repo that we hope to share soon. So I'll close this for now.

**Comment by RubenVanEldik** [comment]
Hi @elitan, super understandable!

I am looking forward to the new repo! Do you already have a rough ETA for the beta of V3?

**Comment by elitan** [comment]
⚠️ Rough estimate ⚠️

~2 months. Maybe sooner.

**Pull request closed without merging**
