### PR TITLE
set default role and allowed roles on registration

### LINKED ISSUE #379: Allow subset of default roles for registration endpoint.
It would be nice to have the registration endpoint accept a parameter that assigns a default role instead of the default `user` role. Something like this:
`auth.register(email, password, { display_name: "Joe Doe" }, 'rolename')`

If this `rolename` does not exist in the `roles` table it will be added.

====== Original idea ====== 

> It would be nice to have the registration endpoint accept a parameter with a subset of the default allowed roles that are defined in the console settings.
> 
> Let's say we have the following default allowed roles defined in the console settings:
> `[1,2,3,4,5]`.
> 
> The registration endpoint would then look like this:
> `auth.register(email, password, { display_name: "Joe Doe" }, [1,2])`
> 
> If no subset is specified all default allowed roles will be assigned to the user.
> 
> Additionally one of the roles in the endpoint parameters could be set as the default role (instead of `user`).

### PR DESCRIPTION
**Pull request by elitan**
Fixes #379

### CODE REVIEW

**Comment by elitan** [comment]
@aaronhayes Want to have a last look before merge?

**Comment by elitan** [comment]
Maybe I'm trying to do too much now but got a v3 proposal for nhost-js-sdk too related to this PR:

https://github.com/nhost/nhost-js-sdk/pull/44

**Comment by aaronhayes** [comment]
> @aaronhayes Want to have a last look before merge?

Changes look fine. Do we need to add some tests?


> Maybe I'm trying to do too much now but got a v3 proposal for nhost-js-sdk too related to this PR:
> 
> [nhost/nhost-js-sdk#44](https://github.com/nhost/nhost-js-sdk/pull/44)

Lots of changes here.  Quick glance looks okay!

**Comment by elitan** [comment]
I'll add some documentation also before merging.

**Pull request merged**
