### PR TITLE
Custom user fields

### PR DESCRIPTION
**Pull request by plmercereau**

### CODE REVIEW

**Comment by elitan** [comment]
I just looked quickly. But it seems like `user_fields` for registration is the same field/data as we use for JWT token custom fields?

I think about it differently.

`user_filds` (or custom registration data) for registration is extra data you want to attach to a user on registration. Such as `name`. 

That data is not necessarily the same data you want to have in your JWT token claims. For a custom JWT Claim you might want to add `organization_id` that is part of the `users` table, which tells what organization the user is part of.

**Comment by elitan** [comment]
For me, there is no direct link between the data you attach to a user at registration, and the custom user fields you want to attach to your JWT token.

**Comment by plmercereau** [comment]
But both would come from the same users table? In that case we could set two separate env vars

**Comment by elitan** [comment]
Ye, we could set two separate env vars. It's just that the data in `users.user_data` could be anything since the client could send anything. Would that be a concern?

**Comment by plmercereau** [comment]
Ok, very god point indeed. So I split `USER_FIELDS` into two environment variables:
- `USER_CLAIMS_FIELDS`: a list of comma separated columns of the `public.users` table, that will be kebab cased, appended with a `x-` prefix and added to the JWT Hasura claims
- `USER_REGISTRATION_FIELDS`: a list of comma separated columns of the `public.users` table, that will be inserted in the record at registration time. Some developers would want to stick the values to a hardcoded SQL schema (like to have a `name` column, an `address` column etc), while some other would want to allow the frontend to send any time of value. In this case, a single `jsonb` column should be defined in the `users` table, and `USER_REGISTRATION_FIELDS` will be the name of this column.

I think it will make everyone happy :)

**Pull request merged**
