### PR TITLE
User Impersonation 

### LINKED ISSUE #250: User impersonation
Is there a mecanism to impersonate/"sign in as a user" for support purposes in HBP?

What would it take to do this?

### PR DESCRIPTION
**Pull request by aaronhayes**
Add support for user impersonation (i.e. Login In As). Useful for support tasks, etc.

I needed a way to provide support to users, hence the PR.

Closes #250 

Changes
 - Added `USER_IMPERSONATION_ENABLE` env variable. Default is value is `false`
 - `/auth/login` accepts a `x-hasura-admin-secret` header which can bypass the password check.
 
 Note:
- This is an opt-in only feature. It is disabled by default.
 - If a user has MFA enabled this will not work.
 
Differences from PR #276
 - Uses `x-hasura-admin-secret` instead of a new `admin-secret` 
 - Opt-in only via env variable.

### CODE REVIEW

**Comment by aaronhayes** [comment]
I may be asked why go with being a "opt-in" feature; I just figured adding a backdoor for user accounts should be optional. Went on the side of caution.

**Comment by elitan** [comment]
We have not forgotten about this PR. It's just a lot on our plates at the moment.

**Comment by aaronhayes** [comment]
> We have not forgotten about this PR. It's just a lot on our plates at the moment.

All good 👍

**Comment by elitan** [comment]
@aaronhayes Can we use `x-admin-secret` instead of `x-hasura-admin-secret` (still same value)? We're already using `x-admin-secret` in the storage modules to bypass permissions.

Everything else looks good. Ready to merge after this change.

**Comment by aaronhayes** [comment]
Sure! Didn't realise `x-admin-secret` was being used else where. Changes have been made. Might be worth rebasing commits?

**Pull request merged**
