### PR TITLE
Add option for rounded images

### PR DESCRIPTION
**Pull request by RubenVanEldik**
Many images (especially avatars) are rounded. By adding the option to remove the parts outside a given radius the size of the image can be minified without compromising the quality. Especially for full rounded images this can be significant, removing over 20% of the image.

### CODE REVIEW

**Comment by RubenVanEldik** [comment]
I think it would be awesome if we're able to create round(ed) images with a single parameter, similar to [Imgix](https://docs.imgix.com/apis/rendering/mask/corner-radius).

I am not able to get the dev version of HBP running on my machine, so I haven't been able to confirm if these changes work, but I think this should do the trick.

**Comment by elitan** [comment]
Thanks for your PR @RubenVanEldik. I'll review and test it locally in the coming days.

Regarding your issue of getting it working locally, maybe you can create a issue on that and I can help you there?

**Comment by RubenVanEldik** [comment]
Thanks! I'll create a new issue for that!

**Comment by RubenVanEldik** [comment]
Never mind, I already found the issue. It was totally my fault, no idea why I didn't figure this out earlier.

**Comment by RubenVanEldik** [comment]
I have ran it locally and fixed some issues. It works!

Schermafbeelding 2021-03-20 om 14 11 54

Schermafbeelding 2021-03-20 om 14 11 33

**Comment by elitan** [comment]
Really nice work with this (and other) PR(s). 

You can run tests locally with:

`./start.sh test --build` to make sure everything is fine. I will try to clean up as I have time here with your PR.

**Pull request merged**
