### PR TITLE
[WIP] Add 2FA (Two Factor Authentication) based on TOTP

### PR DESCRIPTION
**Pull request by mnlbox**
Hi @elitan ,
I finally add 2FA :wink: 
We just need some test, documentation and cleanup.

- [x] Implement 2FA (I implement TOTP apporach but [otplib](https://github.com/yeojz/otplib) also support other approach like HOTP)
- [x] Extract 2FA logic code to a separate file so users can simply modify `sendOTP` function to send TOTP token through SMS, Email, Authenticator app and ...
- [x] Read TOTP setting through new environment variables
- [ ] Add 2FA docs and examples

It's working with TOTP and needs new dependency to: https://github.com/yeojz/otplib

### CODE REVIEW

**Comment by mnlbox** [comment]
This is new environment variables:
```
exports.OTP_ENABLE = process.env.OTP_ENABLE || false; // enable /2fa/generateOTP and /2fa/login and disable /login route
exports.OTP_STEP = process.env.OTP_STEP ? parseInt(process.env.OTP_STEP) : 60; // TOTP time step (seconds)
exports.OTP_SECRET_SALT = process.env.OTP_SECRET_SALT || ''; // Use a strong and not predictable value here
```

**Comment by mnlbox** [comment]
@elitan Any plan to merge this??
This PR is here for near 3 month :thinking:

**Comment by mnlbox** [comment]
@elitan Any progress on this?
This PR just need a simple review.

**Comment by pnfcre** [comment]
Thanks for the work on this, and sorry for the late reply! We took another approach to implementing TOTP in v2 of HBP: https://github.com/nhost/hasura-backend-plus/tree/v2.

**Pull request closed without merging**
